<?php
  if (($children = $this->layout()->getChildren()) && $children[0]?->getTemplate() === 'laminas_whoops/simple_error') {
    echo $this->layout()->content;
    return;
  }
  echo $this->doctype();
?>
<?php
  if (!isset($this->layout()->searchbox)) {
    $this->layout()->searchbox = $this->context($this)->renderInContext('search/searchbox.phtml', []);
  }
?>
<html lang="<?=$this->layout()->userLang?>"<?php if ($this->layout()->rtl): ?> dir="rtl"<?php endif; ?>>
  <head>
    <?php $this->setupThemeResources(); ?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <?=$this->headMeta()?>
    <?=$this->googleTagManager()->getHeadCode()?>
    <?php
      $siteConfig = $this->config()->get('config')->Site;
      $this->headTitle()->setAutoEscape(false);
      $fullTitle = $this->translate(
          'title_wrapper',
          [
            '%%pageTitle%%' => $this->headTitle()->renderTitle(),
            '%%siteTitle%%' => $siteConfig->title,
            '%%titleSeparator%%' => $siteConfig->titleSeparator ?? '::',
          ]
      );
      $this->headTitle()->setAutoEscape(true);
      echo $this->headTitle($fullTitle, \Laminas\View\Helper\Placeholder\Container\AbstractContainer::SET);

      $this->headLink(
          [
            'href' => $this->url('search-opensearch') . '?method=describe',
            'type' => 'application/opensearchdescription+xml',
            'title' => $this->transEsc('Library Catalog Search'),
            'rel' => 'search',
          ]
      );
      $icons = !isset($this->renderingError) ? $this->render('js-icons.phtml') : '{}';
    ?>
    <?php if ($this->layout()->rtl) {
      $this->assetManager()->appendStyleLink('vendor/bootstrap-rtl.min.css');
    } ?>
    <?php
      $appendScripts = [];

      $themeConfig = $this->themeConfig();
      if (!empty($themeConfig['stickyElements'])) {
        $this->assetManager()->appendScriptLink('sticky_elements.js');
      }

      if (!isset($this->renderingError)) {
        $cart = $this->cart();
        if ($cart->isActive()) {
          $this->assetManager()->appendScriptLink('cart.js');
        }
        $this->assetManager()->prependScriptString(
            'var userIsLoggedIn = ' . ($this->auth()->getIdentity() ? 'true' : 'false') . ';'
        );
      }

      if ($this->keepAlive()) {
          $appendScripts[] = 'var keepAliveInterval = ' . $this->keepAlive() . ';';
          $this->assetManager()->appendScriptLink('keep_alive.js');
      }

      $account = $this->auth()->getManager();
      if ($account->ajaxEnabled()) {
        $this->assetManager()->appendScriptLink('account_ajax.js');
        if ($this->session()->put('reset_account_status', null)) {
          $this->assetManager()->appendScriptString(
              script: 'VuFind.account.clearAllCaches();',
              attrs: ['data-lightbox-run' => 'always'],
              options: ['allow_arbitrary_attributes' => true]
          );
        }
      }

      $root = rtrim($this->url('home'), '/');
      $jsConfig = !isset($this->renderingError) ? $this->render('js-configs.phtml') : '{}';
      $translations = !isset($this->renderingError) ? $this->render('js-translations.phtml') : '{}';
      $dsb = DEFAULT_SEARCH_BACKEND;
      $cspNonce = $this->csp()->getNonce();
      $searchId = json_encode($this->layout()->searchId);
      $theme = json_encode($themeConfig['themeName']);

      $appendScripts[] = <<<JS
          VuFind.path = '{$root}';
          VuFind.defaultSearchBackend = '{$dsb}';
          VuFind.config.add({$jsConfig});
          VuFind.addTranslations({$translations});
          VuFind.addIcons({$icons});
          VuFind.setCspNonce('{$cspNonce}');
          VuFind.setCurrentSearchId($searchId);
          VuFind.setTheme($theme);
          JS;

      if ($domain = $this->cookieManager()->getDomain()) {
        $appendScripts[] = 'VuFind.cookie.setDomain(' . json_encode($domain) . ');';
      }
      if ($cookiePath = $this->cookieManager()->getPath()) {
        $appendScripts[] = 'VuFind.cookie.setCookiePath(' . json_encode($cookiePath) . ');';
      }
      if ($cookieSameSite = $this->cookieManager()->getSameSite()) {
        $appendScripts[] = 'VuFind.cookie.setCookieSameSite(' . json_encode($cookieSameSite) . ');';
      }

      if (!empty($lightboxParent)) {
        $lightboxParent = json_encode((string)$lightboxParent);
        $appendScripts[] = 'VuFind.lightbox.parent = ' . $lightboxParent . ';';
      }

      if (!empty($lightboxChild)) {
        $lightboxChild = json_encode((string)$lightboxChild);
        $appendScripts[] = 'VuFind.lightbox.child = ' . $lightboxChild . ';';
      }

      $this->assetManager()->appendScriptString(implode("\n", $appendScripts));
    ?>
    <?=$this->assetManager()->outputHeaderAssets()?>
  </head>
  <body class="template-dir-<?=$this->templateDir?> template-name-<?=$this->templateName?> <?=$this->layoutClass('offcanvas-row')?><?php if ($this->layout()->rtl): ?> rtl<?php endif; ?>">
    <?=$this->cookieConsent()->render('bottom')?>
    <?php if (!isset($this->layout()->searchbox)) {
      $this->layout()->searchbox = $this->render('search/searchbox.phtml');
    } ?>
    <header class="hidden-print">
      <?php if (isset($this->layout()->srmessage)): ?>
        <span class="visually-hidden" role="heading" aria-level="1"><?=$this->layout()->srmessage ?></span>
      <?php endif; ?>
      <a class="visually-hidden-focusable" href="#content"><?=$this->transEsc('Skip to content') ?></a>
      <?=$this->render('header.phtml')?>
    </header>
    <?=$this->breadcrumbs()->render()?>
    <div role="main" class="main">
      <div id="content" class="container">
        <?php if (!($this->layout()->disableDefaultNotices ?? false)): ?>
          <?=$this->notices()->renderNoticesForPosition('default')?>
        <?php endif; ?>
        <?=$this->layout()->content ?>
      </div>
    </div>

    <?=$this->render('footer.phtml')?>

    <!-- MODAL IN CASE WE NEED ONE -->
    <div id="modal" class="modal fade hidden-print" tabindex="-1" role="dialog" aria-label="Modal in case we have extra information" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <button type="button" class="close" data-bs-dismiss="modal" aria-label="<?=$this->transEscAttr('Close')?>">
            <?=$this->icon('lightbox-close')?>
          </button>
          <div class="modal-body"></div>
        </div>
      </div>
    </div>
    <div class="vufind-offcanvas-overlay" data-toggle="vufind-offcanvas"></div>
    <?=$this->googleTagManager()->getBodyCode()?>
    <?=$this->render('Helpers/analytics.phtml')?>
    <?php foreach ($this->captcha()->js() as $jsInclude):?>
      <?=$this->assetManager()->outputInlineScriptLink($jsInclude)?>
    <?php endforeach; ?>

    <?=$this->assetManager()->outputFooterAssets() ?>
  </body>
</html>
