<h1>Welcome to a bit of the TAMU Libraries MSL Catalog</h1>
<p><b>
This is a test instance of VuFind with a very small subset of the MSL Catalog available for browsing.
</b></p>
<div class="searchHomeContent">
  <div class="search-hero" role="search">
    <?php require(__DIR__ . '/../../../bootstrap3/templates/search/home.phtml'); ?>
<!--    <div class="image-credit">
      Yosemite Valley. Photo by <a class="name" href="https://unsplash.com/@heytowner">John Towner</a>.
    </div>-->
  </div>
</div>
